import "./globals.css";
import { AuthProvider } from "@/utils/authContext.js";
import { ThemeProvider } from "@/utils/Theme/ThemeProvider";
import { Toaster } from "react-hot-toast";

import {
  Inter,
  Playfair_Display,
  Manrope,
  Geist_Mono,
} from "next/font/google";

// Main body font
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

// Optional fonts
export const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

export const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
});

// Mono font
const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata = {
  title: "BNB App",
  description: "Generated by create next app",
  icons: {
    icon: "/bbb.ico", // points to public/url.ico
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <AuthProvider>
            {children}

          {/* Toaster UI */}
            <Toaster position="top-right" />
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}